//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBF_Launcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MBF_Launcher.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your quest is not connected via adb yet. Input the pairing code and port shown in the wireless adb pairing page..
        /// </summary>
        public static string AdbNotConnected {
            get {
                return ResourceManager.GetString("AdbNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        public static string AlertDismiss {
            get {
                return ResourceManager.GetString("AlertDismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge Process Terminated.
        /// </summary>
        public static string BridgeProcessTerminated {
            get {
                return ResourceManager.GetString("BridgeProcessTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Device.
        /// </summary>
        public static string CheckingDevice {
            get {
                return ResourceManager.GetString("CheckingDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting on Port {0}.
        /// </summary>
        public static string ConnectingOnPort {
            get {
                return ResourceManager.GetString("ConnectingOnPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting Devices.
        /// </summary>
        public static string DisconnectingDevices {
            get {
                return ResourceManager.GetString("DisconnectingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling Wireless Debugging.
        /// </summary>
        public static string EnablingWirelessDebugging {
            get {
                return ResourceManager.GetString("EnablingWirelessDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Starting Bridge.
        /// </summary>
        public static string ErrorStartingBridge {
            get {
                return ResourceManager.GetString("ErrorStartingBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Selection.
        /// </summary>
        public static string GameSelection {
            get {
                return ResourceManager.GetString("GameSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Devices.
        /// </summary>
        public static string GettingDevices {
            get {
                return ResourceManager.GetString("GettingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granting Permissions.
        /// </summary>
        public static string GrantingPermissions {
            get {
                return ResourceManager.GetString("GrantingPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Developer Settings.
        /// </summary>
        public static string LaunchDeveloperSettings {
            get {
                return ResourceManager.GetString("LaunchDeveloperSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Settings.
        /// </summary>
        public static string LaunchSettings {
            get {
                return ResourceManager.GetString("LaunchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No authorized devices found.
        /// </summary>
        public static string NoAuthorizedDevicesFound {
            get {
                return ResourceManager.GetString("NoAuthorizedDevicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Browser.
        /// </summary>
        public static string OpenBrowser {
            get {
                return ResourceManager.GetString("OpenBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair.
        /// </summary>
        public static string Pair {
            get {
                return ResourceManager.GetString("Pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairing Code:.
        /// </summary>
        public static string PairingCode {
            get {
                return ResourceManager.GetString("PairingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairing was successful! Please enter the wireless debugging port..
        /// </summary>
        public static string PairingSuccessful {
            get {
                return ResourceManager.GetString("PairingSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairing with Device.
        /// </summary>
        public static string PairingWithDevice {
            get {
                return ResourceManager.GetString("PairingWithDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart ADB.
        /// </summary>
        public static string RestartAdb {
            get {
                return ResourceManager.GetString("RestartAdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning For Wireless Debug Port.
        /// </summary>
        public static string ScanningForWirelessDebugPort {
            get {
                return ResourceManager.GetString("ScanningForWirelessDebugPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting TCP IP Mode.
        /// </summary>
        public static string SettingTcpIpMode {
            get {
                return ResourceManager.GetString("SettingTcpIpMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting ADB.
        /// </summary>
        public static string StartingAdb {
            get {
                return ResourceManager.GetString("StartingAdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping ADB.
        /// </summary>
        public static string StoppingAdb {
            get {
                return ResourceManager.GetString("StoppingAdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP/IP Mode.
        /// </summary>
        public static string TcpIpMode {
            get {
                return ResourceManager.GetString("TcpIpMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you didn&apos;t accept a wireless debugging request, or one didn&apos;t appear, make sure you&apos;re connected to a wireless network..
        /// </summary>
        public static string WirelessDebuggingAuthorization {
            get {
                return ResourceManager.GetString("WirelessDebuggingAuthorization", resourceCulture);
            }
        }
    }
}
