//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBF_Launcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MBF_Launcher.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string AlertDismiss {
            get {
                return ResourceManager.GetString("AlertDismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge Process Terminated.
        /// </summary>
        internal static string BridgeProcessTerminated {
            get {
                return ResourceManager.GetString("BridgeProcessTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting on Port {0}.
        /// </summary>
        internal static string ConnectingOnPort {
            get {
                return ResourceManager.GetString("ConnectingOnPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting Devices.
        /// </summary>
        internal static string DisconnectingDevices {
            get {
                return ResourceManager.GetString("DisconnectingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling Wireless Debugging.
        /// </summary>
        internal static string EnablingWirelessDebugging {
            get {
                return ResourceManager.GetString("EnablingWirelessDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Starting Bridge.
        /// </summary>
        internal static string ErrorStartingBridge {
            get {
                return ResourceManager.GetString("ErrorStartingBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Devices.
        /// </summary>
        internal static string GettingDevices {
            get {
                return ResourceManager.GetString("GettingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granting Permissions.
        /// </summary>
        internal static string GrantingPermissions {
            get {
                return ResourceManager.GetString("GrantingPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting TCP IP Mode.
        /// </summary>
        internal static string SettingTcpIpMode {
            get {
                return ResourceManager.GetString("SettingTcpIpMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting ADB.
        /// </summary>
        internal static string StartingAdb {
            get {
                return ResourceManager.GetString("StartingAdb", resourceCulture);
            }
        }
    }
}
