name: Build .NET MAUI App Android

on:
  push:
    branches: [ "*" ]
    tags: [ "v*" ]

  pull_request:
    branches: [ "*" ]

  workflow_dispatch:
    inputs:
      version:
        description: "The version to tag (e.g., v1.0.0). If not provided, it will be extracted from the tag if set."
        required: false
        default: ""

jobs:
  build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.extract_version.outputs.VERSION }}
      pre_release: ${{ steps.extract_version.outputs.PRE_RELEASE }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Extract version from tag or input
      if: startsWith(github.ref, 'refs/tags/') || inputs.version != ''
      id: extract_version
      shell: bash
      run: |
        if [[ "${{ inputs.version }}" != "" ]]; then
          GITHUB_REF_NAME="${{ inputs.version }}"
        else
          GITHUB_REF_NAME="${{ github.ref_name }}"
        fi

        VERSION="${GITHUB_REF_NAME#v}"
        if [[ "$VERSION" == *"-"* ]]; then
          echo "PRE_RELEASE=true" >> $GITHUB_OUTPUT
        else
          echo "PRE_RELEASE=false" >> $GITHUB_OUTPUT
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Setup Keystore File
      shell: bash
      run: |
        echo -n "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > myapp.keystore

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x

    - name: Install .NET MAUI
      run: dotnet workload install maui

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: |
        if ([string]::IsNullOrEmpty("${{ steps.extract_version.outputs.VERSION }}")) {
          & dotnet build "MBF Launcher/MBF Launcher.csproj" `
            -c Release `
            -f net8.0-android34.0 `
            /p:AndroidSigningKeyStore=myapp.keystore `
            /p:AndroidSigningKeyAlias=com.dantheman827.mbflauncher `
            /p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASSWORD }}" `
            /p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD }}" `
            --no-restore
        } else {
          & dotnet build "MBF Launcher/MBF Launcher.csproj" `
            -c Release `
            -f net8.0-android34.0 `
            /p:Version="${{ steps.extract_version.outputs.VERSION }}" `
            /p:AndroidSigningKeyStore=myapp.keystore `
            /p:AndroidSigningKeyAlias=com.dantheman827.mbflauncher `
            /p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASSWORD }}" `
            /p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD }}" `
            --no-restore
        }

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "artifact"
        path: |
          ./MBF Launcher/bin/Release/net8.0-android34.0/com.dantheman827.mbflauncher-Signed.apk

  release:
    if: ${{ needs.build.outputs.version != '' }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: artifact

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *.apk
        tag_name: ${{ needs.build.outputs.version }}
        name: "MBF Launcher ${{ needs.build.outputs.version }}"
        draft: false
        prerelease: ${{ needs.build.outputs.pre_release }}
        target_commitish: ${{ github.sha }}
        generate_release_notes: true
